name: flutter_hbb
description: Your Remote Desktop Software
publish_to: "none"

version: 1.4.2+60

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ffi: ^2.2.0
  path_provider: ^2.3.0
  external_path: ^1.0.4
  provider: ^6.1.5
  tuple: ^2.0.3
  wakelock_plus: ^1.3.0
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.4
  url_launcher_ios: ^6.3.3
  toggle_switch: ^2.3.1
  dash_chat_2:
    git:
      url: https://github.com/rustdesk-org/Dash-Chat-2
      ref: main
  draggable_float_widget: ^0.2.0
  settings_ui: ^2.0.3
  flutter_breadcrumb: ^1.0.2
  http: ^1.3.0
  qr_code_scanner: ^1.1.0
  zxing2: ^0.2.1
  image_picker: ^1.2.0
  image: ^4.2.2
  back_button_interceptor: ^7.0.1
  flutter_rust_bridge: ^1.81.0
  window_manager:
    git:
      url: https://github.com/rustdesk-org/window_manager
      ref: main
  desktop_multi_window:
    git:
      url: https://github.com/rustdesk-org/rustdesk_desktop_multi_window
      ref: main
  freezed_annotation: ^2.5.0
  flutter_custom_cursor: ^0.0.5
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: eb3964990cf19629c89ff8cb4a37640c7b3d5601
  get: ^4.6.7
  visibility_detector: ^0.4.2
  contextmenu: ^3.0.1
  desktop_drop: ^0.5.0
  scroll_pos: ^0.4.1
  debounce_throttle: ^2.1.0
  file_picker: ^8.1.1
  flutter_svg: ^2.0.11
  uni_links:
    git:
      url: https://github.com/rustdesk-org/uni_links
      path: uni_links
      ref: main
  uni_links_desktop: ^0.1.7
  path: ^1.9.0
  auto_size_text: ^3.0.1
  bot_toast: ^4.1.3
  win32: ^5.6.0
  password_strength: ^0.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_keyboard_visibility: ^6.0.1
  texture_rgba_renderer:
    git:
      url: https://github.com/rustdesk-org/flutter_texture_rgba_renderer
      ref: main
  percent_indicator: ^4.2.3
  dropdown_button2: ^2.3.9
  flutter_gpu_texture_renderer:
    git:
      url: https://github.com/rustdesk-org/flutter_gpu_texture_renderer
      ref: main
  uuid: ^4.6.0
  auto_size_text_field: ^2.2.1
  flex_color_picker: ^3.4.0
  dynamic_layouts:
    git:
      url: https://github.com/rustdesk-org/dynamic_layouts.git
      ref: main
  pull_down_button: ^0.9.4
  device_info_plus: ^10.1.0
  qr_flutter: ^4.1.1
  extended_text: ^14.0.1
  xterm: ^4.0.1
  sqflite: ^2.4.0
  google_fonts: ^6.2.3

dev_dependencies:
  icons_launcher: ^2.0.5
  build_runner: ^2.4.10
  freezed: ^2.5.7
  flutter_lints: ^3.0.1
  ffigen: ^9.0.1

dependency_overrides:
  intl: ^0.19.0
  flutter_plugin_android_lifecycle: ^2.0.19

flutter_icons:
  image_path: "../res/icon.png"
  remove_alpha_ios: true
  android: true
  ios: true
  windows:
    generate: true
  macos:
    image_path: "../res/mac-icon.png"
    generate: true
  linux: true
  web:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: GestureIcons
      fonts:
        - asset: assets/gestures.ttf
    - family: Tabbar
      fonts:
        - asset: assets/tabbar.ttf
    - family: PeerSearchbar
      fonts:
        - asset: assets/peer_searchbar.ttf
    - family: AddressBook
      fonts:
        - asset: assets/address_book.ttf
    - family: DeviceGroup
      fonts:
        - asset: assets/device_group.ttf
    - family: More
      fonts:
        - asset: assets/more.ttf
